### ISSUE TITLE
Class permission

### ISSUE THREAD

**Issue by unusorin** [1up-lab/OneupAclBundle#17]
Hi,
I'm trying to set up this acl manger with doctrine ODM on Symfony 2.5. Everything seems to work but I've noticed that the class permissions are not working. Basically, I've annotated my document like

```
     @Acl\DomainObject({
         @Acl\ClassPermission({ "ROLE_ADMIN" = MaskBuilder::MASK_IDDQD })
       })
```

, but when I check permissions with `isGranted` using a normal user, it allows me to create a new document. Do you have any ideas about this issue ? 

Thanks.

**Comment by GreGosPhaTos** [comment]
I Have a similar issue : 

```yaml
security:
      acl:
        connection: default
        voter:
          allow_if_object_identity_unavailable: false
```

And when I do 

```php
$aclManager->setClassPermission('My\\Class\\Name', MaskBuilder::MASK_VIEW, $user);

// always returns false 
$aclManager->isGranted('VIEW', 'My\\Class\\Name')
```
isGranted returns always false ... Did I missed something ?
